# Generated by Django 4.2.16 on 2025-02-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application_deadline',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='result',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='priority',
            field=models.CharField(choices=[('High', 'high'), ('Medium', 'medium'), ('Low', 'low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
